package com.neo.mapper;

import java.util.List;

import org.apache.ibatis.annotations.*;

import com.neo.entity.UserEntity;
import com.neo.enums.UserSexEnum;

@Mapper
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu Sep 06 23:16:38 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu Sep 06 23:16:38 CST 2018
     */
    int insert(UserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu Sep 06 23:16:38 CST 2018
     */
    UserEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu Sep 06 23:16:38 CST 2018
     */
    List<UserEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu Sep 06 23:16:38 CST 2018
     */
    int updateByPrimaryKey(UserEntity record);


    @Select("select * from user where username=#{name} and password = #{password}")
    UserEntity selectByUserNameAndPassword(@Param("name") String name, @Param("password") String password);
}
